{{- $ns := .Values.namespace | default "default" -}}
{{- range $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $svc.name }}
  namespace: {{ $ns }}
spec:
  type: ClusterIP
  selector:
    app: {{ $svc.name }}
  ports:
    - port: 80
      targetPort: {{ $svc.port }}
      protocol: TCP
---
{{- end }}



