{{- $ns := .Values.namespace | default "default" -}}
{{- range $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $svc.name }}
  namespace: {{ $ns }}
spec:
  selector:
    app: {{ $svc.name }}
  ports:
    - protocol: TCP
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
  type: ClusterIP
---
{{- end }}




