global:
  registry: docker.io/najemkub
  imagePullSecretName: dockerhub-cred
  imagePullPolicy: IfNotPresent

namespace: default

services:
  - name: frontend
    image: skillverse-frontend:latest
    port: 80
    replicaCount: 1
  - name: gateway-service
    image: gateway-service:latest
    port: 8080
    replicaCount: 1
  - name: auth-service
    image: auth-service:latest
    port: 8080
    replicaCount: 1
  - name: profil-service
    image: profil-service:latest
    port: 8080
    replicaCount: 1
  - name: chat-service
    image: chat-service:latest
    port: 8080
    replicaCount: 1
  - name: matching-service
    image: matching-service:latest
    port: 8080
    replicaCount: 1
  - name: booking-service
    image: booking-service:latest
    port: 8080
    replicaCount: 1
  - name: reputation-service
    image: reputation-service:latest
    port: 8080
    replicaCount: 1
  - name: discovery-service
    image: discovery-service:latest
    port: 8761
    replicaCount: 1

ingress:
  enabled: true
  hostname: placeholder.local
  tls:
    secretName: tls-secret





