name: CI - Notification Service

on:
  push:
    branches: [ main, develop, feature/*, chore/* ]
    paths:
      - 'backend/notification-service/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/ci-notification.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/notification-service/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/ci-notification.yml'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Profil "test" pour CI (ex: désactiver Firebase)
    env:
      SPRING_PROFILES_ACTIVE: test

    defaults:
      run:
        working-directory: backend/notification-service

    steps:
      # 1) Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Java + cache Maven
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3) Rendre mvnw exécutable (Linux)
      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      # 4a) Sur branches feature/* : tests unitaires
      - name: Run Unit Tests (feature/*)
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: ./mvnw -B -ntp test


      # 4b) Sur develop/main/PR : suite complète
      - name: Run Full Test Suite (develop/main/PR)
        if: |
          github.event_name == 'pull_request' ||
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/main'
        run: ./mvnw -B -ntp verify
       # 5) Scan SonarCloud (qualité) sur feature / develop / main / PR
      - name: SonarCloud Scan
        if: |
         github.ref == 'refs/heads/develop' ||
         github.ref == 'refs/heads/main' ||
         github.event_name == 'pull_request'
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # auto de GitHub
         SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}    # toi tu l'ajoutes dans GitHub secrets
        run: |
          ./mvnw -B -ntp org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=nadia-2004 \
            -Dsonar.projectKey=nadia-2004_Plateforme-Skillverse
        # 6) Trivy — Scan FS (code + dépendances + Dockerfile + secrets)
      - name: Trivy FS Scan (code & deps)
        if: startsWith(github.ref, 'refs/heads/feature/')||
            github.event_name == 'pull_request' ||
            github.ref == 'refs/heads/develop' ||
            github.ref == 'refs/heads/main' ||
            github.event_name == 'workflow_dispatch'
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          path: .
          scanners: vuln,secret,config
          format: table
          exit-code: '1'                 # ❗ fail le job si CVE selon 'severity'
          severity: 'MEDIUM,HIGH,CRITICAL'
          ignore-unfixed: true           # optionnel mais recommandé

